### ISSUE TITLE
Are the separate macOS setup lines necessary?

### ISSUE THREAD

**Issue by cyberwizard1001** [cyberwizard1001/workshop-practise#10]

**Comment by cyberwizard1001** [comment]
@sridhar-5, are the steps for configuration of GitHub Desktop different enough from that of the Windows one to have two different headers for both of em?

**Comment by radiantly** [comment]
GitHub desktop setup is quite user-friendly, do we need configuration steps in the first place :thinking:

**Comment by sridhar-5** [comment]
I don't think. it's very different. Not necessary

**Comment by cyberwizard1001** [comment]
Okay.. so, we retain a common setup guide for both OSes and scrap the Windows/mac version. @sridhar-5 Can you?

@radiantly It might come in useful for someone xD

**Comment by sridhar-5** [comment]
sure, @cyberwizard1001. so I should be writing a separate readme for setup? I believe it's already there, isn't?

**Comment by cyberwizard1001** [comment]
@sridhar-5 There's a duplication in the initial readme. 1.SettingUpGit.md

**Comment by sridhar-5** [comment]
I think separate steps are not required. people can find very minor changes which they can figure out. I don't think we should have separate installation steps for Mac. If there is a duplication I will edit it tomorrow.
